# Vectors

## How to set up a vector

A vector is an ordered set of numeric data.

Python has a library designed, among other things, for working with vectors. It's called Numeric Python, or NumPy for short. It implements a huge number of functions for mathematical calculations.

A vector in NumPy is an object of a special type called an array. To create such an object, you call the NumPy library function of the same name:

In [1]:
import numpy as np

In [2]:
v = np.array([2, 15, 6])

In [3]:
v

array([ 2, 15,  6])

## Addition and subtraction of vectors

In arithmetic, we add and subtract numbers, in algebra, we add and subtract variables, and in linear algebra, we perform the same operations with vectors. Moreover, vectors can be added and subtracted, as well as defined, algebraically and geometrically.

In [4]:
# addition
january = np.array([648, 371, 338.4, 512, 0, 437, 11])
february = np.array([112, 380, 516, 294, 108, 380, 65])
march = np.array([506, 0, 412, 98, 304, 811, 56])

s = january + february + march
print(s)

[1266.   751.  1266.4  904.   412.  1628.   132. ]


In [5]:
# substraction
income = np.array([2.8, 4.31, 3.75, 5.4, 5.98, 4.9, 3.11, 4.5, 5.24, 4, 3.8, 6.11])
outcome = np.array([2.3, 2.3, 2.2, 4.2, 3.7, 3.25, 3.2, 4.11, 3.87, 2.9, 2.65, 3.3])
print(income - outcome)

[ 0.5   2.01  1.55  1.2   2.28  1.65 -0.09  0.39  1.37  1.1   1.15  2.81]


In [6]:
# multiplication
a = np.array([3.7, 4.8, 4.2, 7.2, 7.6])
c = 1.2 * a
print(c)

[4.44 5.76 5.04 8.64 9.12]


In [7]:
# division
salary = np.array([60000, 100000, 80000, 65000, 73000])
print(salary / 15)

[4000.         6666.66666667 5333.33333333 4333.33333333 4866.66666667]


## Dot product of vectors

The scalar product of two vectors is the product of their lengths and the cosine of the angle between them.

In [8]:
a = np.array([5, 4, 8])
b = np.array([7, 12, 6])
c = a @ b
print(c)

131


## Linear combination of vectors

Vectors, like other objects, form sets. One way to define a set is to define properties that all its elements satisfy. These properties must uniquely identify the elements of the set: if elements possess the set's properties, they are included in it; if they lack at least one, they are not included.

In [9]:
a = np.array([45, 21, 6, 0, 18, 5])
b = np.array([-6, 11, 8, 32, 9, 115])
c = np.array([1, 2, 3, 4, 5, 6])
d = np.array([318, 4, 0, 0, 0, -7])

k1, k2, k3, k4 = 3, 11, -5, 7

l = k1 * a + k2 * b + k3 * c + k4 * d
print(l)

[2290  202   91  332  128 1201]


## How to calculate vector's norm

In [10]:
# L1 норма
import numpy as np

k = np.array([25, -41, -31, 66])
l1 = np.linalg.norm(k, 1) # Вызываем функцию norm() из np.linalg .
print(l1)

163.0


In [8]:
# L1 норма
from numpy import array # Подключение функции array() из numpy.
from numpy.linalg import norm # Подключение функции norm() из numpy.linalg.

k = array([8, -16, -4, 5]) # Теперь не нужно писать np.
l1 = norm(k, 1)
print(l1)

33.0


In [9]:
# L2 норма
from numpy import array
from numpy.linalg import norm 

k = array([8, -16, -4, 5])
l2 = norm(k, 2)
print(l2)

19.0


In [10]:
# Максимальная норма
from numpy import array
from numpy import inf  # Подключаем бесконечность.
from numpy.linalg import norm

k = array([8, -16, -4, 5])
maxnorm = norm(k, inf)
print(maxnorm)

16.0


## How to find the angle between vectors 

In [2]:
from numpy import array
from numpy import arccos
from numpy import rad2deg  
from numpy.linalg import norm

a = array([4, 8, 17])
b = array([-2, 3, 7])
cos_angle = a @ b / norm(a) / norm(b)
angle = arccos(cos_angle) 
print("Косинус угла между a и b:", cos_angle) # В кавычках, через запятую.
print("Сам угол:", rad2deg(angle))  # В кавычках, через запятую.

Косинус угла между a и b: 0.8925339417277717
Сам угол: 26.80659154352711


In [7]:
# допишите код здесь
import numpy as np
from numpy import array
from numpy import arccos
from numpy import rad2deg  
from numpy.linalg import norm

k = np.array([12, 8, 3, 1])
l = np.array([0.7, 22, 5, 9])

# допишите код здесь
k = array([4, 8, 17])
l = array([-2, 3, 7])
cos_angle = k @ l / norm(k) / norm(l)
angle = arccos(cos_angle) 

print("Косинус угла между k и l:", cos_angle)# допишите код здесь
print("Сам угол:", angle) # допишите код здесь

Косинус угла между k и l: 0.8925339417277717
Сам угол: 0.4678632836718169


## Calculating Distances in Python

In [1]:
from numpy import array
from numpy import inf
from numpy.linalg import norm

a = array([22, 4, -6, 3.9, 7])
b = array([12, -0.5, 6, 42, 1])

r_1 = norm(a - b, 1)  # Вычисление L1 расстояния.
r_2 = norm(a - b, 2)  # Вычисление L2 расстояния.
r_max = norm(a - b, inf)  # Вычисление максимального расстояния.

print("L1 расстояние между векторами a и b:", r_1)  # Вывод на экран L1 расстояния.
print("L2 расстояние между векторами a и b:", r_2)  # Вывод на экран L2 расстояния.
print(
    "Максимальное расстояние между векторами a и b:", r_max
)  # Вывод на экран максимального расстояния.

L1 расстояние между векторами a и b: 70.6
L2 расстояние между векторами a и b: 41.85522667481327
Максимальное расстояние между векторами a и b: 38.1


## Cosine distance

In [11]:
from numpy import array
from numpy.linalg import norm

o_1 = array([-4, 6, 12])
o_2 = array([2, -8, 3])
o_3 = array([5, 3, -1])
cos_1_2 = o_1 @ o_2 / norm(o_1) / norm(o_2)
cos_1_3 = o_1 @ o_3 / norm(o_1) / norm(o_3)
cos_2_3 = o_2 @ o_3 / norm(o_2) / norm(o_3)
print("Отзывы 1 и 2:", cos_1_2)
print("Отзывы 1 и 3:", cos_1_3)
print("Отзывы 2 и 3:", cos_2_3)

Отзывы 1 и 2: -0.16280082351376848
Отзывы 1 и 3: -0.1690308509457033
Отзывы 2 и 3: -0.32746850462500326


## Tests

In [5]:
from numpy import array
from numpy import inf
from numpy.linalg import norm

a = array([(8, −16, −4, 5)])

r_1 = norm(a, 1)  # Вычисление L1 расстояния.
r_2 = norm(a, 2)  # Вычисление L2 расстояния.
r_max = norm(a, inf)  # Вычисление максимального расстояния.

print("L1 расстояние между векторами a и b:", r_1)  # Вывод на экран L1 расстояния.
print("L2 расстояние между векторами a и b:", r_2)  # Вывод на экран L2 расстояния.
print(
    "Максимальное расстояние между векторами a и b:", r_max
)  # Вывод на экран максимального расстояния.

SyntaxError: invalid character '−' (U+2212) (1462911430.py, line 5)