# Vectors

## How to set up a vector

A vector is an ordered set of numeric data.

Python has a library designed, among other things, for working with vectors. It's called Numeric Python, or NumPy for short. It implements a huge number of functions for mathematical calculations.

A vector in NumPy is an object of a special type called an array. To create such an object, you call the NumPy library function of the same name:

In [1]:
import numpy as np

In [2]:
v = np.array([2, 15, 6])

In [3]:
v

array([ 2, 15,  6])

## Addition and subtraction of vectors

In arithmetic, we add and subtract numbers, in algebra, we add and subtract variables, and in linear algebra, we perform the same operations with vectors. Moreover, vectors can be added and subtracted, as well as defined, algebraically and geometrically.

In [5]:
# addition
january = np.array([648, 371, 338.4, 512, 0, 437, 11])
february = np.array([112, 380, 516, 294, 108, 380, 65])
march = np.array([506, 0, 412, 98, 304, 811, 56])

s = january + february + march
print(s)

[1266.   751.  1266.4  904.   412.  1628.   132. ]


In [6]:
# substraction
income = np.array([2.8, 4.31, 3.75, 5.4, 5.98, 4.9, 3.11, 4.5, 5.24, 4, 3.8, 6.11])
outcome = np.array([2.3, 2.3, 2.2, 4.2, 3.7, 3.25, 3.2, 4.11, 3.87, 2.9, 2.65, 3.3])
print(income - outcome)

[ 0.5   2.01  1.55  1.2   2.28  1.65 -0.09  0.39  1.37  1.1   1.15  2.81]


In [7]:
# multiplication
a = np.array([3.7, 4.8, 4.2, 7.2, 7.6])
c = 1.2 * a
print(c)

[4.44 5.76 5.04 8.64 9.12]


In [8]:
# division
salary = np.array([60000, 100000, 80000, 65000, 73000])
print(salary / 15)

[4000.         6666.66666667 5333.33333333 4333.33333333 4866.66666667]


## Dot product of vectors

The scalar product of two vectors is the product of their lengths and the cosine of the angle between them.

In [9]:
a = np.array([5, 4, 8])
b = np.array([7, 12, 6])
c = a @ b
print(c)

131


## Linear combination of vectors

Vectors, like other objects, form sets. One way to define a set is to define properties that all its elements satisfy. These properties must uniquely identify the elements of the set: if elements possess the set's properties, they are included in it; if they lack at least one, they are not included.

In [11]:
a = np.array([45, 21, 6, 0, 18, 5])
b = np.array([-6, 11, 8, 32, 9, 115])
c = np.array([1, 2, 3, 4, 5, 6])
d = np.array([318, 4, 0, 0, 0, -7])

k1, k2, k3, k4 = 3, 11, -5, 7

l = k1 * a + k2 * b + k3 * c + k4 * d
print(l)

[2290  202   91  332  128 1201]
